apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes: 
  - ReadWriteOnce
  hostPath:
    path: /drupal-mysql-data